### ISSUE TITLE
Use update_fields in serializer's update

### ISSUE THREAD

**Issue by SafaAlfulaij** [encode/django-rest-framework#7619] opened 2020-10-28 18:37 UTC
It seems that any update (even partial updates) update the full instance instead of just the needed fields.

https://github.com/encode/django-rest-framework/blob/04e0c2b9ab6616a28148ce32e2d19858ccfe6c69/rest_framework/serializers.py#L983

This seems a better approach:
```python
        direct_attrs = []
        m2m_fields = []
        for attr, value in validated_data.items():
            if attr in info.relations and info.relations[attr].to_many:
                m2m_fields.append((attr, value))
            else:
                direct_attrs.append(attr)
                setattr(instance, attr, value)

        instance.save(update_fields=direct_attrs)
```

**Comment by ErwinJunge** [comment] 2020-11-04 15:44
This is a duplicate of https://github.com/encode/django-rest-framework/issues/2648 which holds a good discussion on the topic.

**Closed** 2020-11-06 05:58 UTC
