### ISSUE TITLE
Instantiating view with as_view in setUpClass results in AssertionError

### ISSUE THREAD

**Issue by dms-cat** [encode/django-rest-framework#6738] opened 2019-06-11 02:04 UTC
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. Put `cls.view = MyViewSet.as_view(actions={"post": "some_action"}, detail=True)` in a test class's `setUpClass` method.
1. Run `self.view(self.request, pk=self.some_object.id)` in a test.

## Expected behavior

It should work identically to `self.view = MyViewSet.as_view(actions={"post": "some_action"}, detail=True)` in a test class's `setUp` method.

## Actual behavior

I get the following error message:

> AssertionError: The `request` argument must be an instance of `django.http.HttpRequest`, not `[package name].[test class name]`.

Creating the view in the `setUp` method works just fine.

## Details

Based on a bit of debugging the `view` field is created differently. When initialized in `setUpClass`, `self.view` ends up being `<bound method MyViewSet of <[package name].[test class name] testMethod=[method name]>>`, but when created in `setUp` it is `<function MyViewSet at 0x7f0a5515ac80>`.

**Comment by xordoquy** [comment] 2019-06-11 05:42
Yup, could reproduce the issue.
It looks like there's a lot of magic going around `TestCase` which makes things tricky to use there.
Workaround is to use `YourTestCase.view(...)` instead of `self.view(...)` thought I've seen teardown failures with "type object 'MyTestCase' has no attribute 'cls_atomics'" which also happen with Django's generic views.
Provided it has issues with Django generic views - though there are less issues -, provided it works with `<TestCase>.<view>` and provided I don't see a reason to call `as_view` in the `setUpClass` rather than `setUp` I'm going to close this.
We will be considering PR to fix the described issue based on their own merit.

**Closed by xordoquy** 2019-06-11 05:42 UTC

**Comment by rpkilby** [comment] 2019-06-11 16:11
Is this an issue with CBV's generally, or is there something specific with DRF that is causing this to fail?

**Comment by dms-cat** [comment] 2019-06-11 21:21
I'm calling `as_view` in `setUpClass` to speed up the tests by only instantiating the view once. Isn't that a valid reason?

**Comment by xordoquy** [comment] 2019-06-11 21:40
If speed is an issue, don't call the view through `as_view` and unit test the functions directly
