### ISSUE TITLE
3.15 regression: ListSerializer ValidationError nested structure silently changed

### ISSUE THREAD

**Issue by peterthomassen** [encode/django-rest-framework#9318] opened 2024-03-21 03:29 UTC
#8863 changed the nested dict/list structure of ValidationError detail. I know this is the intention of #8863, but it does break code that parses exception details.

Note that much of that code is on the client side, which often cannot easily be comprehensively tested centrally (unlike backend-side parsing). This causes an unknown amount of misrendered error messages that lose their utility to human users. (And not only that; programmatic handling of structured errors of course breaks as well.)

This is a breaking change in a public-facing data structure and should be reverted.

**Comment by tomchristie** [comment] 2024-03-21 14:07
Thanks, yes.
Let's treat this a duplicate of #9317.

**Closed by tomchristie** 2024-03-21 14:07 UTC
Labels: 3.15.1
