### ISSUE TITLE
Validated data issue

### ISSUE THREAD

**Issue by jgrewal1991** [encode/django-rest-framework#7623] opened 2020-11-03 17:11 UTC
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
1. Create Serializer using BaseSerializer
2. create serializer_obj and call serializer_obj.save()(Make sure to have breakpoint before https://github.com/encode/django-rest-framework/blob/master/rest_framework/serializers.py#L197) 
3. Use your serializer in Viewset and make a post call to the endpoint. Make sure you call with FormData as body.
Example values:
`
  'name': '2020.pdf'
  'type': 1
  'creator': 'asdfga69-cdgaba-46e5-bfdge-da2fgdsfac77'
  'additional_data': {'designation': 2, 'date': '2020-11-01', 'number': 'dafsda'}
`
4. Once you hit breakpoint

## Expected behavior
validate_data == request.POST
{'name': '2020.pdf', 'type': 1, 'creator': 'asdfga69-cdgaba-46e5-bfdge-da2fgdsfac77', 'additional_data': {'designation': 2, 'date': '2020-11-01', 'number': 'dafsda'}}

## Actual behavior
form of validated in changed,
{'name': ['2020.pdf'], 'type': [1], 'creator': ['asdfga69-cdgaba-46e5-bfdge-da2fgdsfac77'], 'additional_data': [{'designation': 2, 'date': '2020-11-01', 'number': 'dafsda'}]}

**Comment by xordoquy** [comment] 2020-11-03 17:34
I'm closing this because I can not reproduce.
Using the tutorial's repository and DRF master (updated today), altering DRF code to print type and content of the `validated_data` after https://github.com/encode/django-rest-framework/blob/master/rest_framework/serializers.py#L197:

```
<class 'dict'>
{'title': 'a', 'code': 'ab', 'linenos': False, 'language': 'abap', 'style': 'abap'}
```

Associated request:

```
PUT /snippets/1/ HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryt8w5DzYu4kdqUawY
Accept: text/html; q=1.0, */*
Accept-Language: fr-fr
Accept-Encoding: gzip, deflate
Host: localhost:8000
Origin: http://localhost:8000
Content-Length: 426
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0 Safari/605.1.15
Referer: http://localhost:8000/snippets/1/
Connection: keep-alive
Cookie: csrftoken=****; sessionid=****; session=****; remember_token=****
X-Requested-With: XMLHttpRequest
X-CSRFTOKEN: *****


------WebKitFormBoundaryt8w5DzYu4kdqUawY
Content-Disposition: form-data; name="title"

a
------WebKitFormBoundaryt8w5DzYu4kdqUawY
Content-Disposition: form-data; name="code"

abc
------WebKitFormBoundaryt8w5DzYu4kdqUawY
Content-Disposition: form-data; name="language"

abap
------WebKitFormBoundaryt8w5DzYu4kdqUawY
Content-Disposition: form-data; name="style"

abap
------WebKitFormBoundaryt8w5DzYu4kdqUawY--
```

And got:

```
<class 'dict'>
{'title': 'a', 'code': 'ab', 'linenos': False, 'language': 'abap', 'style': 'abap'}
```

**Closed by xordoquy** 2020-11-03 17:34 UTC

**Comment by xordoquy** [comment] 2020-11-03 17:37
BTW, printing the `self.validated_data` before the line gives:

```
<class 'collections.OrderedDict'>
OrderedDict([('title', 'a'), ('code', 'ab'), ('linenos', False), ('language', 'abap'), ('style', 'abap')])
```
