### ISSUE TITLE
Response NaN is not handled correctly

### ISSUE THREAD

**Issue by bekerov** [encode/django-rest-framework#5444] opened 2017-09-24 16:02 UTC
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
```
import numpy as np
from rest_framework.response import Response
analisys = {'raw_images': np.NaN}
return Response(analisys, status=200, content_type='application/json')
```
## Expected behavior
I expected what response body is 
```
{"raw_images": null}
```

## Actual behavior
I get this invalid json and i cannot handle this response in JS
```
{"raw_images": NaN}
```

**Comment by carltongibson** [comment] 2017-09-24 16:33
Duplicate of #5235.

**Closed by carltongibson** 2017-09-24 16:33 UTC
