### ISSUE TITLE
Broken file links in docs

### ISSUE THREAD

**Issue by meshy** [encode/django-rest-framework#5945] opened 2018-04-19 16:03 UTC
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Look at top of docs page.

## Expected behavior

See links to relevant files on github.

## Actual behavior

![screenshot from 2018-04-19 17-00-19](https://user-images.githubusercontent.com/767671/39003790-848de6a4-43f3-11e8-93cc-4b31a35fb125.png)

**Comment by tomchristie** [comment] 2018-04-19 16:05
What the heck. When and how did *that* happen?

**Comment by tomchristie** [comment] 2018-04-19 16:11
Rebuilt with MkDocs 0.16

https://github.com/encode/django-rest-framework/commits/gh-pages

Have confirmed that build with latest version results in the broken behavior.

**Comment by tomchristie** [comment] 2018-04-19 16:12
I'll close this since the docs are fixed for now, and raise this against the mkdocs repo.

**Comment by meshy** [comment] 2018-04-19 16:12
Awesome, thanks for the quick response! `:)`

**Closed by tomchristie** 2018-04-19 16:12 UTC

**Comment by tomchristie** [comment] 2018-04-19 16:15
Thanks for raising it! 😄
