### ISSUE TITLE
Cannot send form data in documentation API

### ISSUE THREAD

**Issue by dczech** [encode/django-rest-framework#5100] opened 2017-04-26 18:26 UTC
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
In documentation API try sending any form with required fields.

## Expected behavior
Form is sent and results are correctly displayed.

## Actual behavior
Form is not sent. Javascript error occurs: `Error: Missing required field: "fieldname"  coreapi-0.1.0.js:527:51` (at least on Firefox)

This is related with bug introduced in #5001 Please check comments to [0fdaf4f481b4c6c3c22bd4c1fe1dfc6f8d9b1475]

**Comment by carltongibson** [comment] 2017-09-28 07:32
I can't reproduce this in Firefox, Chrome or Safari. 

> In documentation API try sending any form with required fields.

Using a `CreateAPIView` with 3 required fields, in all three browsers, I'm successfully submitting the request with a `201 Created` response as expected. 

I'm going to close this. I'm happy to re-open if we can pin down a reproduce. (Ideally I think we need a test project with exact steps here — these frontend issues are hard to capture otherwise.)

> @dczech right, entries can be either an iterator or an array. I think we can get away with using for...of in there.
> — @jpadilla https://github.com/encode/django-rest-framework/commit/0fdaf4f481b4c6c3c22bd4c1fe1dfc6f8d9b1475#commitcomment-21799440
 
@jpadilla It seemed you had a grip on the issue there. Any chance you could advise? 🙂

**Closed by carltongibson** 2017-09-28 07:32 UTC
Labels: Bug, Interactive API Documentation
