### ISSUE TITLE
ListField html widget does not handle empty well

### ISSUE THREAD

**Issue by beruic** [encode/django-rest-framework#5601] opened 2017-11-16 13:44 UTC
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Create a serializer with the below field, and submit it with no content in the browsable API
```python
    words = serializers.ListField(
        child=serializers.CharField(),
        allow_empty=True,
        required=False,
    )

```
## Expected behavior
The `validated_data` is either not pressen or an empty list.

## Actual behavior
You get an error that "This field may not be blank".
This error message pertains the child `CharField`. Setting the child  `allow_blank=True` results in a list with the empty string.

**Comment by xordoquy** [comment] 2017-11-16 13:56
I don't think `ListField` supports the browsable API - or the other way around.
I'm closing this as the expected behavior would be the browsable API don't show the "detail" form.

**Closed by xordoquy** 2017-11-16 13:56 UTC

**Comment by beruic** [comment] 2017-11-16 14:35
Well... It does show up in the browsable API form.

**Comment by xordoquy** [comment] 2017-11-16 14:37
@beruic you probably mean, the widget representing the `ListField` while I said the full "detail" form should not be shown.

**Comment by beruic** [comment] 2017-11-16 19:27
Then I guess I don't know what you mean @xordoquy. What exactly do you mean by the full "detail" form?

**Comment by xordoquy** [comment] 2017-11-16 19:57
The form at the bottom of the [page](http://www.django-rest-framework.org/img/quickstart.png)

**Comment by beruic** [comment] 2017-11-16 20:27
That's the form I am talking about. Custom words in this screenshot is a `ListField` with `CharField` child:
![jk-dev_8000_search_](https://user-images.githubusercontent.com/724716/32914112-b76fe1a6-cb14-11e7-85b7-50b850231109.png)

The HTML is `<input name="custom_words" class="form-control" type="text">`

**Comment by beruic** [comment] 2017-11-16 20:33
I have updated the issue description to make it clearer.

**Comment by beruic** [comment] 2017-11-17 13:24
@xordoquy Think it would be possible to reopen, or is it still not clear enough?

I have also experienced another issue with this input field. It won't accept input from the detail form correctly. No matter what I input it is always perceived as a single list entry, rather than more. If I input raw JSON it works fine.

**Comment by carltongibson** [comment] 2017-11-20 09:05
Hi @beruic, 

Looking at what you've got here it looks like you want/need to accept a CSV list `wordA,wordB,wordC` or such — much like [`django.contrib.postgres provides for `ArrayField`](https://docs.djangoproject.com/en/dev/ref/contrib/postgres/forms/#postgresql-specific-form-fields-and-widgets). 

I think if you craft up a custom widget that parses the CSV into a list you may get the result you need. 

But you're going to need to play here and see what works. 

As it stands this isn't an addressable issue for us. It's not clear that we support ListField for the Browsable API — just simply because HTML forms don't map neatly to nested data structures. 

If you make good progress we're happy to take contributions and link to third-party packages etc.

**Comment by beruic** [comment] 2017-11-20 11:13
Thank you for the answer @carltongibson.

Well, it just feels a bit inconsistent. If I use the [built in API documentation](http://www.django-rest-framework.org/topics/documenting-your-api/) pages instead (which is what I have defaulted to now), the field works fine and consistently. It shows `[ ]` by default and accepts sane input like `["my", "words"]` without any trouble.

**Comment by carltongibson** [comment] 2017-11-20 11:21
Ah, but the API documentation uses the coreapi JS client to send JSON requests, whereas the Browsable API sends HTML forms. Different tech. Different limitations.

**Comment by beruic** [comment] 2017-11-20 12:06
Ok. I think the coreapi way is cleaner, but I will look into the issue if I get time later. Right now I'm over my head :)
