### ISSUE TITLE
`query_params` is a property of the DRF request object, but not the request object returned by APIRequestFactory

### ISSUE THREAD

**Issue by tstirrat15** [encode/django-rest-framework#6488] opened 2019-03-04 23:29 UTC
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
```python
from rest_framework.test APIRequestFactory

def test_request_factory_get_request_has_query_params():
  assert APIRequestFactory().get('/', { 'foo': 'bar' }).query_params
```
## Expected behavior
Pass

## Actual behavior
AttributeError

Is there an easy way around this? Otherwise, is there a place/way that you'd prefer me to make the necessary modifications?

**Comment by carltongibson** [comment] 2019-03-05 08:07
This looks like a Duplicate of #4440. That was close but this comment was added: 

https://github.com/encode/django-rest-framework/issues/4440#issuecomment-244053745

> Aside: I have warmed to the idea of ensuring that this returns a fully fledged Request instance, and having views be able to handle either, so this might come up in the future.

Probably time to fix that...

**Comment by rpkilby** [comment] 2019-03-06 21:04
At a minimum, we need an easy way of creating fully fledged DRF requests. Several of our tests use dummy views to get the fully created request/response/view instance. 

https://github.com/encode/django-rest-framework/blob/739b0a272a66d9beb7afb7490f201d71d7cdc910/tests/test_renderers.py#L733-L746

That said, any solution would need to initialize the fully fledged DRF request *with* a view, given that the DRF request needs to be initialized with the view's authenticators, permissions, etc...

What I'm thinking is the factory could provide a helper that returns the request, response and view instance all at once. I don't think we could return a fully fledged request without going through the whole view lifecycle, since this gets back to the issue of double parsing the underlying request body.

**Comment by striveforbest** [comment] 2021-12-15 23:50
is there still no good solution to this?

**Comment by sliverc** [comment] 2022-04-18 07:21
I think this issue is still relevant and to fix this would improve testing of DRF.

**Comment by sliverc** [comment] 2022-06-25 13:16
This is still relevant. Unfortunately no time to work on a PR myself but maybe someone else does.

**Comment by reify-tanner-stirrat** [comment] 2022-11-02 02:34
Still relevant.

**Comment by auvipy** [comment] 2023-01-07 15:38
contribution to fix this, would be highly appreciated.

**Comment by carltongibson** [comment] 2024-04-11 05:41
I think this should be resolved with an example in the docs. 

It's the View's responsibility to convert the Django request to a DRF request. 

Using the `Client` this is transparent: the request is passed through `dispatch()` and it all happens automatically. 

The request factory comes in when you want to test a view method by hand. 

But then, rather than calling dispatch, you'll instantiate the view manually, before calling the method under test. 

The key point is you'll need to call `initial` by-hand in this case anyway, to prepare the view. It's one extra line to initialise the request as well. 

There no way of transparently mapping the request to a DRF request which isn't going to break a whole load of expectations here.

**Comment by tomchristie** [comment] 2024-04-11 15:17
As @carltongibson says, this behavior isn't going to change.

If someone's invested and there's clearly a good existing place in the docs to highlight this, then we could accept a docs PR here.

**Closed by tomchristie** 2024-04-11 15:17 UTC
Labels: Cleanup
