### ISSUE TITLE
Model viewset/serializer choice field default value not selected in browsable api (latest 3.9.4)

### ISSUE THREAD

**Issue by alexandre-paroissien** [encode/django-rest-framework#6760] opened 2019-06-27 06:56 UTC
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Create a model with a choice field (non-nullable and non-blank charfield), for example priority = low / normal / high. Create a model viewset and a model serializer,

## Expected behavior
In browsable api the POST form should select the default value (normal) such as django admin model creation page is doing, so that the instance will be created with default value if the user does not touch the dropdown.

## Actual behavior
In browsable api in latest DRF (3.9.4) the POST form is selecting the first value by default (low) instead of the default one (normal). The instance is created with non-default value if the user does not touch the dropdown.

**Comment by Offpics** [comment] 2019-06-27 14:39
Maybe you don't provide [initial parameter](https://www.django-rest-framework.org/api-guide/fields/#initial) to the ChoiceField?

**Comment by xordoquy** [comment] 2019-06-27 15:06
The `BrowsableAPI` will not use model's default values and indeed your use case could lead to some unwanted side effects.
The issue is valid to me but I'm still going to close this because the core team will likely not have the time to work on it.
A PR about this issue will be considered on its own merit.

**Closed by xordoquy** 2019-06-27 15:06 UTC
