### ISSUE TITLE
authenticate vs has_permission (missunderstanding and not clear functions) and custom api_key/token

### ISSUE THREAD

**Issue by ManPython** [encode/django-rest-framework#7396] opened 2020-06-30 23:50 UTC
DJ 2.2.6
Due to some missunderstanding and not clear functions as `authenticate` vs `has_permission` and regrading this issues:
https://github.com/encode/django-rest-framework/issues/355
a) https://stackoverflow.com/questions/33560552/django-rest-framework-authentication-require-key-parameter-in-url
b) https://stackoverflow.com/questions/29433416/token-in-query-string-with-django-rest-frameworks-tokenauthentication
.. I made some "research" (including google group) how devs doing solution for `?api_key=` that can be features or way to change something in DRF

1. There is conflict when `?api_key=` as short `TOKEN` is sugested as `JWT` with long string/hashes even short is more friendly
2. Users want `TOKEN`, soo.. devs doing clasess, eg.
a) as in link a) and they using `has_permission` - that is not the same like `authenticate`
b) as in link b) and they using `authenticate` - that is not the same like `has_permission`
3. In both of a), b) they using `?api_key=` in `request`

- bellow both 4,5 points with `has_permission` function
4. Next devs adding in `'DEFAULT_PERMISSION_CLASSES': ( 'api.utils.permissions.OnlyAPIPermission',` 
- this made that in option a) API working if user is logged and `?api_key=` is provided, but when user is not loged then any of `?api_key=` not working for views ( `"Authentication credentials were not provided."`) similar like a bad token/key 
- they starting experiments with `permission_classes = (OnlyAPIPermission,)` and `@permission_classes((OnlyAPIPermission, ))` that not working
5. Due this like in point 4. after analysis the situation they changig settings for `'DEFAULT_AUTHENTICATION_CLASSES':  ( 'api.utils.permissions.OnlyAPIPermission',` - as experiment (premission, now authentication needed), and not workig
6. Again..following point 5. after.. they change  `has_permission` for  `authenticate` in the class, but this not changing nothing (around premission or authenticate) for loged user, but when user is not loged then error:
```
Exception Type: | TypeError
authenticate() missing 1 required positional argument: 'view'
Python36\lib\site-packages\rest_framework\request.py in _authenticate, line 373
```
- ok.. delete `view` that is required in `def has_permission(self, request, view):` to made (`def authenticate(self, request):`) and have access as not loged user, where in fact the `TOKEN` related with user made this user as loged. In case of this, user not only get access to API, eg. for feeding some app client by data, but manage maybe related customer panel or something in realtion to django admin (the range of managment and access is not limited and not offering this way by `authenticate`). 
- Hvr.. in case of "whole access" is not true, there is not well described or not explained log **Forbidden:** in message that giving `"detail": "Authentication credentials were not provided."` in situation where acess should be granted and authenticated, and is near `/api/` in case of `/api/v1` etc working - **need explanation here (why this doing, and when)** and working normaly if not using this whole solution for token/key

7. Soo.. the conflit is around `authenticate`  and `has_permission`, coz access by `TOKEN` should be like permission for some part of app, eg API, but not as full authentication. It's more like secuirity issue then. This is in case of not only `CustomUser` solution. -
- looks like in DRF can't be `permission ` without `authenticate` in this way for the `TOKEN` must be diffrent
8. Due this conflict devs goint work with https://pypi.org/project/djangorestframework-api-key/ 
- this solution require to build new models and tokens called directly `key`, and with option as multiple key per user that is often required
- due of this, devs discovering situation that they reinventing whell as new DRF and TOKEN : )
- in case of nature this `path` for DRF is no sense to "shadowing" fork by custom_keys as package but in fact require to copy fork as part project and modify (reinventing for showdowing is no sense)
9. Soo.. due of this all complication in my opinion and way what devs doing want sugest some changes in DRF to solve problems

- [ ] implement something like 
- Token_Permission
- Token_Authentication
- merge option for authenticate and has_permission as similar (point 6)
- clarify the `authenticate_credentials` in return with request on relation to premissions grants, and describe this in docs
- [ ] or implement KEY_ACCESS as in relation to upper TOKEN (as the best way) or Key_Permission / Key_Authentication
- including custom keys with aditional parameteres
- including multiple keys per user as upper
- or in both way in relation to one user PK or more for user rows as cols TOKEN, KEY, JWT

## Steps to reproduce
use `def authenticate(self, request):` with

```
class TokenAuthSupportQueryString(TokenAuthentication):
    """
    Extend the TokenAuthentication class to support querystring authentication
    in the form of "http://www.example.com/?auth_token=<token_key>"
    """
    def authenticate(self, request):
        # Check if 'token_auth' is in the request query params.
        # Give precedence to 'Authorization' header.
        if 'auth_token' in request.QUERY_PARAMS and \
                        'HTTP_AUTHORIZATION' not in request.META:
            return self.authenticate_credentials(request.QUERY_PARAMS.get('auth_token'))
        else:
            return super(TokenAuthSupportQueryString, self).authenticate(request)
```
- check the range `**Forbidden:**` 
## Expected behavior
- not limiting urls paterns by `**Forbidden:** ` 

## Actual behavior
- limiting urls paterns by `**Forbidden:** ` in begin api/ (in this level can be swagger, etc. and exist conflit)

**Comment by xordoquy** [comment] 2020-07-01 07:07
Hi,

Unfortunately the issue is not actionnable in its current form and looks like a usage question for which the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take to discuss.
I'm going to close it for that reason.
A failing test case similar to those used for [`TokenAuthentication`](https://github.com/encode/django-rest-framework/blob/d7b218f5eba78a99ae202e10c5d4b4d186735f7d/tests/authentication/test_authentication.py#L288-L297) would greatly help understand the actual issue and reconsider.

**Closed by xordoquy** 2020-07-01 07:07 UTC
