### ISSUE TITLE
get_schema_view raise exceptions.PermissionDenied() with particular urlpatterns.

### ISSUE THREAD

**Issue by fakepoet** [encode/django-rest-framework#6007] opened 2018-05-29 07:48 UTC
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Just start a single app django project including 2 or more urls having same prefix, set a url for get_schema_view, then request the url.
Following below, I sure you will reproduce this.

the project tree:
```shell
test_proj/
├── db.sqlite3
├── manage.py
├── test_app
│   ├── __init__.py
│   ├── __pycache__
│   ├── admin.py
│   ├── apps.py
│   ├── migrations
│   ├── models.py
│   ├── tests.py
│   ├── urls.py
│   └── views.py
├── test_proj
│   ├── __init__.py
│   ├── __pycache__
│   ├── settings.py
│   ├── urls.py
│   └── wsgi.py
└── venv
    ├── bin
    ├── include
    ├── lib
    └── pip-selfcheck.json
```
test_app/views.py:
```python
from rest_framework import viewsets, serializers
from rest_framework.response import Response
from rest_framework.decorators import action


class TestSerializer(serializers.Serializer):
    a = serializers.IntegerField()


class TestViewSet(viewsets.GenericViewSet):
    serializer_class = TestSerializer

    @action(['GET'], detail=False)
    def test1(self):
        return Response({})

    @action(['GET'], detail=False)
    def test2(self):
        return Response({})
```
test_app/urls.py:
```python
from rest_framework.routers import SimpleRouter
import test_app.views as views

router = SimpleRouter()
router.register('test', views.TestViewSet, 'test')

urlpatterns = router.urls
```
test_proj/urls.py:
```python
from django.conf.urls import url, include
from django.contrib import admin
from rest_framework.schemas import get_schema_view

schema_view = get_schema_view('API')

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^api/', schema_view),
    url(r'^test', include('test_app.urls')),
]
```

## Expected behavior
Should get a normally schema view.

## Actual behavior
The get_schema_view raised exceptions.PermessionDenied()./

## Further debug
 I've reproduced this bug for many times, and digged into source code for a while, then I find the bug, `get_schema_view` func use `SchemaGenerator.get_schema` method, if this method return None, then the PermissionDenied will be raised.
 in `rest_framework.SchemaGenerator.get_schema`:
```python
links = self.get_links(None if public else request)
        if not links:
            return None
```
further in `SchemaGenerator.get_links`:
```python
        for path, method, view in view_endpoints:
            print(path, method, view)
            if not self.has_view_permissions(path, method, view):
                continue
            link = view.schema.get_link(path, method, base_url=self.url)
            subpath = path[len(prefix):]
            keys = self.get_keys(subpath, method, view)
            insert_into(links, keys, link)
```
and even further in `rest_framework.schemas.generators.insert_into`:
```python
def insert_into(target, keys, value):
    """
    Nested dictionary insertion.

    >>> example = {}
    >>> insert_into(example, ['a', 'b', 'c'], 123)
    >>> example
    LinkNode({'a': LinkNode({'b': LinkNode({'c': LinkNode(links=[123])}}})))
    """
    for key in keys[:-1]:
        if key not in target:
            target[key] = LinkNode()
        target = target[key]

    try:
        target.links.append((keys[-1], value))
    except TypeError:
        msg = INSERT_INTO_COLLISION_FMT.format(
            value_url=value.url,
            target_url=target.url,
            keys=keys
        )
        raise ValueError(msg)
```
This `insert_into` func does not react like it's annotation. When there's only one key, it's supposed to make target= `LinkNode({'key': LinkNode(links=[value])})`, but this code will make target=`LinkNode(links=[('key', 'value')])`, which caused `not target` == `Ture`.
By alter this `insert_into` func will repaire the bug, but I'm not sure if the repaire is correct, so I put what I've got here and hope this bug get further discusses, Thanks.

**Comment by mrgaolei** [comment] 2018-05-29 07:52
me too

**Comment by carltongibson** [comment] 2018-05-29 09:36
Hi @fakepoet. Thanks for the report. I'll have a look into it.

**Comment by carltongibson** [comment] 2018-10-02 14:50
I haven't had a chance to look into this as yet. I'm not going to block v3.9 on it though, as it seems something of an edge-case. 

I'd be very happy to see the example turned into a failing test case, and even a fix, in a PR!

**Comment by alexander-jacob** [comment] 2019-02-01 12:49
I don't think that is something of an edge-case.
A stateless api without a model should work as described by @fakepoet

**Comment by alexander-jacob** [comment] 2019-02-02 16:11
As @fakepoet already noted 
```python
generators.insert_into(target, keys, value)
``` 
does not produce the expected result with `len(keys)==1`

Maybe the problem is in 
```python
SchemaGenerator.determine_path_prefix(self, paths)
```
If paths is i.e. `['/foo/bar/baz/test1', '/foo/bar/baz/test2']` then `determine_path_prefix` will result in `'/foo/bar/baz'`. `insert_into` will be called with `keys=['baz']` which results in the error described above.

By replacing in `determine_path_prefix` 
`prefix = '/'.join(initial_components[:-1])` with `prefix = '/'.join(initial_components[:-2])`
then we'll have in any case `len(keys)>=2`. To test it try:
```python
class SchemaGeneratorFix(SchemaGenerator):
    def determine_path_prefix(self, paths):
        prefixes = []
        for path in paths:
            components = path.strip('/').split('/')
            initial_components = []
            for component in components:
                if '{' in component:
                    break
                initial_components.append(component)
            prefix = '/'.join(initial_components[:-2]) ## <-- single change here
            if not prefix:
                return '/'
            prefixes.append('/' + prefix + '/')
        return common_path(prefixes)

schema_view = get_schema_view(title='TestAPI', generator_class=SchemaGeneratorFix)
```

**Comment by carltongibson** [comment] 2019-02-02 17:20
> ...`generators.insert_into()` ... does not produce the expected result...

Anyone fancy putting an actual unit test in a pull request showing the incorrect behaviour?

**Comment by fakepoet** [comment] 2019-05-05 05:26
@carltongibson It's been a long time since last discuss, I've been stuck with some personal stuffs...anyway, I manage to add a new test case to reproduce this issue, would you like to take a look at it? 

@alexander-jacob I tried your suggestion and it turned out to break two test cases, I'm steal trying to find a way to fix it, hope for further discusses with you.

**Comment by fakepoet** [comment] 2019-05-05 06:14
Managed to fix this, hope for code review from you guys  : )

**Comment by carltongibson** [comment] 2020-04-06 13:51
Closing as per #6685

**Closed by carltongibson** 2020-04-06 13:51 UTC
Labels: Schema Generation
