### ISSUE TITLE
Automatic timezone conversion for aware datetime values

### ISSUE THREAD

**Issue by muhammedabad** [encode/django-rest-framework#5067] opened 2017-04-10 07:14 UTC
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

It seems like datetime values that are timezone aware are not converted to the default timezone by the serializer, even when `USE_TZ` is set to `True`. Is there any way around this to prevent me doing this conversion manually on the client side ?

**Comment by rpkilby** [comment] 2017-04-10 18:31
Hi @muhammedabad - this seems to be a duplicate of #3732. If not, could you provide more detail as to what the actual and expected behavior are?

**Closed by rpkilby** 2017-04-10 18:31 UTC
