### ISSUE TITLE
django multi app the doc won't show up

### ISSUE THREAD

**Issue by tyan4g** [encode/django-rest-framework#5298] opened 2017-07-29 06:57 UTC
## Steps to reproduce
I have 2 apps in a django project. one is auth, another is live

```
urlpatterns = [
    url(r'^auth/', include('qxauth.urls')),
    url(r'^live/', include('qxlive.urls')),
    url(r'^docs/', include_docs_urls('API Documentation')),
]
```

but when I open the 
locahost:8000/docs
it will only show the apps name,
no content will be show.

unless I commented out another apps url
```
urlpatterns = [
    url(r'^auth/', include('qxauth.urls')),
    # url(r'^live/', include('qxlive.urls')),
    url(r'^docs/', include_docs_urls('API Documentation')),
]
```

then I can see the doc 
## Expected behavior
I should see the doc of auth app and live app
## Actual behavior
the doc genarated is blank, and no errors in the console..

**Comment by anshengme** [comment] 2017-07-29 14:41
#5299

可以交流一下

**Comment by tyan4g** [comment] 2017-07-31 03:04
@anshengme 你们也遇到了这个问题吗？

**Comment by anshengme** [comment] 2017-07-31 03:19
@tyan4g 是的,不过已经放弃使用了,等更成熟的时候在使用.

**Comment by tyan4g** [comment] 2017-08-02 06:01
@anshengme Now we basic using API view and the wrapped request and response, 
and I think the serilaizer is pretty helpful when validate the incoming data. 
I mean our company using only part of it . while combine with the business logic and the rest framework just not enough.

**Comment by carltongibson** [comment] 2017-08-15 12:46
There's not enough for me to go on here I'm afraid. I can't reproduce the issue from what you've provided. I'm going to have to close the issue pending more details. Thanks.

**Closed by carltongibson** 2017-08-15 12:46 UTC
