### ISSUE TITLE
AssertionErrors lack location of problem

### ISSUE THREAD

**Issue by AndreasBackx** [encode/django-rest-framework#6946] opened 2019-09-23 22:35 UTC
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Unknowingly make a mistake in one of your serializers.

## Expected behavior

For DRF to tell you what field in what serializer lies the problem.

## Actual behavior

It only tells you the problem, not where the problem is. For example the assertions made in [`Field.__init__`](https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L321-L324). Setting a field to both `read_only` and `read_write` will result in the following error (stacktrace omitted):

```
AssertionError: May not set both `read_only` and `write_only`
```

The stacktrace does not help you with the problem as this these serializers are "dynamic" (for lack of a better term I guess). It would be much more useful if it were to add which ones were the problem:

```
AssertionError: May not set both `read_only` and `write_only` in MySerializer.my_field
```

Came across this error and I found it a bit frustrating to debug so I thought I'd report it here.

**Comment by hawzie197** [comment] 2019-09-27 19:39
1. At this time, we are unable to get access to the Serializer field_name and parent, as it is set later on in the bind method, found on line 355 in [rest_framework/fields.py](https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py). The .bind() method is executed inside the BindDict() found inside the Serializer class definition found on line 359 in rest_framework/serializers.py.
2. Traceback is sufficient enough to find the causing Serializer/field. For example, please see below:

Created test to run example serializers
`
class Parent(serializers.Serializer):
    f1 = serializers.CharField()

class Child(serializers.Serializer):
    parent = Parent(read_only=True, write_only=True)
`
Traceback is given below
`
tests/test_serializer.py:699: in test_read_write_correct_class_and_field
    class Child(serializers.Serializer):
tests/test_serializer.py:700: in Child
    parent = Parent(read_only=True, write_only=True)
rest_framework/serializers.py:117: in __init__
    super().__init__(**kwargs)
rest_framework/fields.py:321: in __init__
    assert not (read_only and write_only), NOT_READ_ONLY_WRITE_ONLY
E   AssertionError: May not set both `read_only` and `write_only`
`
You can find the Parent serializer, field and reference line 3 traces up.

Best,

Michael

**Comment by carltongibson** [comment] 2019-09-27 19:42
Great. Thanks for the analysis @hawzie197! 

I agree, the location of the error is easy enough to spot in the traceback, and you're right, the `parent` is not available here. 

Let's call it `wontfix` on that basis. 👍

**Closed by carltongibson** 2019-09-27 19:42 UTC

**Comment by AndreasBackx** [comment] 2019-09-27 22:16
> Traceback is sufficient enough to find the causing Serializer/field. For example, please see below:

The example provided uses very basic serializers that do not generate their actual field classes. The ModelSerializer does this for example and it does not give any indication as to what field is referred to by the assertion error, see [`serializers.ModelSerializer.get_fields()`](https://github.com/encode/django-rest-framework/blob/master/rest_framework/serializers.py#L989). I do not know the entire inner workings, but the `field_name` seems to be passed to `build_field` which might allow it to be used in the assertion error. Regardless, I am not knowledgeable enough on the DRF source to propose any implementation details for this.

> I agree, the location of the error is easy enough to spot in the traceback, and you're right, the parent is not available here.

@carltongibson, based on the above, could the issue be reopened?

**Comment by xordoquy** [comment] 2019-09-28 01:39
There's a point I still don't understand. By default, `ModelSerializer` fields are R/W. The only cases I can think of are:
- using `extra_args` to set both `read_only`/`write_only`
- explicitly defining the field and settings both.
What use case am I missing ?

**Comment by AndreasBackx** [comment] 2019-09-28 12:55
@xordoquy there are still other assertions made in the code as well, the issues is to add this info to all assertions. I also don't really understand your question as the issue refers to assertion info, not the assertion in the example.

**Comment by xordoquy** [comment] 2019-09-28 21:25
We need to get something more accurate to make choices.
In its current form, the issue is not actionable.
Do you have a list of assertions that cause that issue and a test case for each so we can review them and figure out whether or not it's actually an issue ?

**Comment by carltongibson** [comment] 2019-09-30 10:26
Also, still, the parent serializer is not available on the field at the point the exception is raised, so digging it out is going to be overly complex at best.

Use the traceback, or, if you really are doing something super dynamic so that’s not realistic, catch the AssertionError and re raise with more info.

**Comment by rpkilby** [comment] 2019-09-30 18:34
The error handling could potentially be improved here. Per @xordoquy's comment, I assume the user has provided `extra_kwargs` that conflict with the generated defaults. We could wrap this line in a try/catch, which should allow us to reraise the original assertion with the class/field name.

https://github.com/encode/django-rest-framework/blob/0dac98d21571bee1232666f2b101de3ff4ed4c9e/rest_framework/serializers.py#L1055

----

@AndreasBackx if you can provide a concrete example of a model serializer that generates the error, I'd be happy to take a look at fixing this.

**Comment by xordoquy** [comment] 2019-10-01 09:00
@AndreasBackx take care of yourself first !
If the issue is important enough someone will be able to spent some time on it to go further :)
