### ISSUE TITLE
NamespaceVersioning raises 'Request' object has no attribute 'version' exception

### ISSUE THREAD

**Issue by hamzawaqas-10p** [encode/django-rest-framework#3278] opened 2015-08-17 06:59 UTC
I've written the following line in my APIView method:

``` python
print(request.version);
```

while, my settings.py looks something like this:

```
REST_FRAMEWORK = {
    'TEST_REQUEST_DEFAULT_FORMAT': 'json',
    'TEST_REQUEST_RENDERER_CLASSES': (
        'rest_framework.renderers.MultiPartRenderer',
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.TemplateHTMLRenderer'
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # 'core.authentication.TokenAuthentication',
      # 'rest_framework.authentication.BasicAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        # 'core.permission.IsNotAnonymous',
    ),
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
    'DEFAULT_VERSION': 'v1',
    'EXCEPTION_HANDLER': 'core.error.custom_exception_handler'
}

```

And, that's how my routes looks like:

```
urlpatterns = [
    url(r'^', include('api.urls')),
    url(r'^r', REndpoint.as_view()),
    url(r'^v1/', include('api.urls', namespace='v1')),
]
```

And, `api.urls` is as follow:

```
router.register(r'notifications', NotificationsEndpoint, 'Notifications')

urlpatterns = [
    url(r'^', include(router.urls)),
    # ....
]
```

When I try to hit the route with `/v1/groups` or `/v1/notifications` with `POST`, it reaches my method which is just printing the version. Means, `version` attribute has not been set on the `Request` object.

**Comment by tomchristie** [comment] 2015-08-20 15:46
I'm not exactly clear on what "it reaches my method" specifically means - which method?

It's possible that this is due to having your URLconf set up incorrectly, so that your first 'api.urls' is matching the request, rather than the namespaced `v1` entry.

**Comment by AndreasBackx** [comment] 2015-08-24 13:03
I have a similar problem. The following will silence a `'Request' object has no attribute 'version'` exception:

```python
class SomeRetrieveView(generics.RetrieveAPIView):
    '''Retrieve a single something.'''

    authentication_classes = (CustomAuthentication,)
    queryset = Some.objects.all()

    def get_serializer_class(self):
        if self.request.version > 1:
            return SomeSerializer
        else:
            return SomeSerializerOld
```

This will not:

```python
class SomeRetrieveView(generics.RetrieveAPIView):
    '''Retrieve a single something.'''

    authentication_classes = (CustomAuthentication,)

    def get_queryset(self):
        self.request.user
        return Some.objects.all()

    def get_serializer_class(self):
        if self.request.version > 1:
            return SomeSerializer
        else:
            return SomeSerializerOld
```

Calling [self.request.user](https://github.com/tomchristie/django-rest-framework/blob/f087dcf7e2644f530db5d524ce71d818cca3a326/rest_framework/request.py#L399-L417) is somehow different from when the request.user is never called.

**Comment by rpkilby** [comment] 2018-05-20 06:35
Hi all. I've tried to recreate this in a test case and have been unable to recreate the original error. Given that the issue is over three years old, and versioning generally seems to be working for most users, I'm going to close this as "probably fixed in a more recent version". If you're still having issues, a complete test case would be greatly appreciated.

**Closed by rpkilby** 2018-05-20 06:35 UTC
Labels: Needs further review
