### ISSUE TITLE
nullable custom field with source='*' raises exception on to_internal_value

### ISSUE THREAD

**Issue by videda** [encode/django-rest-framework#6609] opened 2019-04-26 10:35 UTC
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
models.py:
```python
    from django.db import models

    class TestModel(models.Model):
        testattribute = models.CharField(max_length=30)
```

serializers.py:

```python
    from rest_framework import serializers
    from . import models

    class TestField(serializers.Field):

        def to_representation(self, instance):
            return getattr(instance, 'testattribute', None)

        def to_internal_value(self, data):
            return {'testattribute': data}

    class TestSerializer(serializers.ModelSerializer):

        testattribute = TestField(source='*', allow_null=True)

        class Meta:
            fields = (
                'testattribute',
            )
            model = models.TestModel
```

In the `python manage.py shell` execute:

```
    from app1.serializers import TestSerializer
    s = TestSerializer(data={'testattribute': None})
    s.is_valid()
```

## Expected behavior

`s.is_valid()` should return True

## Actual behavior
Exception:

```
   Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "[...]/test/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 236, in is_valid
        self._validated_data = self.run_validation(self.initial_data)
      File "[...]/test/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 434, in run_validation
        value = self.to_internal_value(data)
      File "[...]/test/venv/lib/python3.7/site-packages/rest_framework/serializers.py", line 501, in to_internal_value
        set_value(ret, field.source_attrs, validated_value)
      File "[...]/test/venv/lib/python3.7/site-packages/rest_framework/fields.py", line 126, in set_value
        dictionary.update(value)
    TypeError: 'NoneType' object is not iterable
```

**Comment by rpkilby** [comment] 2019-05-09 02:02
Related issues are #3451, #5635. Note that a workaround can be found in https://github.com/encode/django-rest-framework/issues/5635#issuecomment-383312843.

**Comment by rpkilby** [comment] 2019-05-09 02:03
I'm going to go ahead and close as a duplicate of those. I'm also about to submit a PR.

**Closed by rpkilby** 2019-05-09 02:03 UTC
