### ISSUE TITLE
PrimaryKeyRelatedField with read_only=True will always be documented as type="string"

### ISSUE THREAD

**Issue by KevinPoole** [encode/django-rest-framework#7427] opened 2020-07-24 17:14 UTC
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

Have a serializer with a PrimaryKeyRelatedField that ends up getting inspected to generate an OpenAPI schema.

## Expected behavior

When using the default PK (which is an integer) the type should be documented as an integer whether it is read_only or not.

## Actual behavior

Type is documented as an integer when not read_only, but as a string when it is read_only.

I tracked down the root cause for this, but am not familiar enough with the project to understand what the preferred solution would be.

You can see [here](https://github.com/encode/django-rest-framework/blob/599e2b183db846a632b1efd148e6bc97d926ee5c/rest_framework/schemas/openapi.py#L380) that if there is a queryset specified whose model has an AutoField as a PK (already seems oddly specific, but oh well) then the type will be specified as an integer. But the issue is that [here](https://github.com/encode/django-rest-framework/blob/599e2b183db846a632b1efd148e6bc97d926ee5c/rest_framework/relations.py#L111) in RelationField you are not permitted to specify a queryset and read_only at the same time (as a sanity check I assume?) and so read_only PrimaryKeyRelatedField's are always relegated to strings it seems.

Open to thoughts on the proper fix.

**Comment by AndrewGuenther** [comment] 2021-05-22 01:28
I just ran into a similar issue with the same root cause. If you have a primary key that is anything other than an AutoField it will always serialize as a string. This causes many client generators to throw errors because the key will likely serialize as a different type when returned.

I would imagine this is fixable by making a recursive call into `field_to_schema` and I'm a bit curious why that wasn't done in the first place?

Effectively change this block:
https://github.com/encode/django-rest-framework/blob/master/rest_framework/schemas/coreapi.py#L283-L290

To this:

```python
elif isinstance(field, serializers.PrimaryKeyRelatedField):
        schema_cls = coreschema.String
        model = getattr(field.queryset, 'model', None)
        if model is not None:
            schema_cls = type(field_to_schema(model._meta.pk))
        return schema_cls(title=title, description=description)
```

Unfortunately, that doesn't fix the case where queryset isn't set, but it is at least _more_ correct than what's there now... Would be nice to have a maintainer chime in on this.

**Comment by auvipy** [comment] 2022-12-15 12:09
as the open api is deprecated so closing this

**Closed by auvipy** 2022-12-15 12:09 UTC
Labels: Schema Generation
