### ISSUE TITLE
Field in schema with DateTimeField isn't generated as date-time type.

### ISSUE THREAD

**Issue by NN---** [encode/django-rest-framework#6091] opened 2018-07-23 14:19 UTC
## Checklist

- [X] I have verified that that issue exists against the `master` branch of Django REST framework.
- [X] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [X] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [X] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [X] I have reduced the issue to the simplest possible case.
- [X] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
Add DateTimeField to REST API.

## Expected behavior
myurl/schema should provide JSON with field saying it is date-time and not just any string.

## Actual behavior
```json
       "name": "myDate",
                    "required": true,
                    "location": "form",
                    "schema": {
                        "_type": "string",
                        "title": "MyDate",
                        "description": ""
                    }
```

**Comment by carltongibson** [comment] 2018-07-24 12:13
Duplicate of #5511.

**Closed** 2018-07-24 12:16 UTC
Labels: Schema Generation

**Comment by NN---** [comment] 2018-07-24 20:50
Are there any expectations when this will be working with django release ?
