### ISSUE TITLE
Markdown extension no longer supports markdown.version

### ISSUE THREAD

**Issue by mlissner** [encode/django-rest-framework#6210] opened 2018-09-24 20:28 UTC
DRF has the following code:

https://github.com/encode/django-rest-framework/blob/master/rest_framework/compat.py#L164-L172

It relies on `markdown.version`. In Markdown 3.0, which was published a few days ago, that no longer works, and it throws an attribute error. 

I filed https://github.com/Python-Markdown/markdown/issues/711 in hopes that it'd get resolved in Markdown, but I'm filing this bug so that everybody is aware of the issue.

**Comment by mbaragiola** [comment] 2018-09-24 21:08
I got the same issue and fixed it by forcing `markdown==2.6.11` on my pip requirements, just in case someone is struggling with it.

**Comment by mlissner** [comment] 2018-09-24 21:12
Yep, I just added this to my requirements.txt file:

Markdown~=2.6

**Comment by rpkilby** [comment] 2018-09-25 01:12
Hi @mlissner - closing this as a duplicate of #6203.

**Closed by rpkilby** 2018-09-25 01:12 UTC
