### ISSUE TITLE
collectstatic Post-processing 'rest_framework\css\bootstrap-theme.min.css' failed! even after installing whitenoise latest version 

### ISSUE THREAD

**Issue by osadolortech** [encode/django-rest-framework#8608] opened 2022-08-16 07:08 UTC
## Checklist

-when i was using Django 4.0.6 i was able to use the compressed manifest static storage and collect static was fine but when i moved to Django 4.1 i ran collect static i started getting errors when using compress manifest
![issues](https://user-images.githubusercontent.com/91027519/184825992-c4acaa4e-7736-40f6-877d-b0bf7a362472.PNG) 

i think is because files are not compressed and no unique name for each version

- WhiteNoise comes with a storage backend which automatically takes care of compressing your files and creating unique names for each version so they can safely be cached forever. To use it, you have to add it at the bottom of your settings, it should be the last line in settings.py STATICFILES_STORAGE = "whitenoise.storage.CompressedStaticFilesStorage"
![issue](https://user-images.githubusercontent.com/91027519/184818802-71475c59-ef5c-4b33-8939-1d170201b92e.PNG)
this solves the problem.

**Comment by kevin-brown** [comment] 2022-08-16 20:17
I believe this is a duplicate of https://github.com/encode/django-rest-framework/pull/8591 which has been fixed in the next version.

**Closed** 2022-08-16 20:17 UTC
