### ISSUE TITLE
Import utils.six error on relations.py

### ISSUE THREAD

**Issue by wangxujie** [encode/django-rest-framework#5738] opened 2018-01-10 14:08 UTC
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [x] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
clone master and import into IDE,

## Expected behavior
works perfect

## Actual behavior

import error in sevenral py's file. example : 

```
'compat.py' ,'settings.py':
"ImportError: Could not import 'rest_framework.renderers.JSONRenderer' for API setting 'DEFAULT_RENDERER_CLASSES'. 
ImportError: No module named urls." 
```

, like this; and many didn't found on anthor module;

**Comment by carltongibson** [comment] 2018-01-10 15:28
> ... import into IDE...

What does this mean? You need to specify the exact steps to reproduce your issue. 

I cannot reproduce this like so: 

```
Last login: Mon Jan  8 11:04:00 on ttys001
~ $ python3 -m venv ~/Desktop/drf-test
~ $ source ~/Desktop/drf-test/bin/activate
(drf-test) ~ $ pip install djangorestframework
Collecting djangorestframework
  Downloading djangorestframework-3.7.7-py2.py3-none-any.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 106kB/s 
Installing collected packages: djangorestframework
Successfully installed djangorestframework-3.7.7
(drf-test) ~ $ pip install Django
Collecting Django
  Downloading Django-2.0.1-py3-none-any.whl (7.1MB)
    100% |████████████████████████████████| 7.1MB 138kB/s 
Collecting pytz (from Django)
  Downloading pytz-2017.3-py2.py3-none-any.whl (511kB)
    100% |████████████████████████████████| 512kB 697kB/s 
Installing collected packages: pytz, Django
Successfully installed Django-2.0.1 pytz-2017.3
(drf-test) ~ $ python
Python 3.6.0 (default, Sep  9 2017, 14:57:57) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.35)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from django.conf import settings
>>> settings.configure(SECRET_KEY='123abc')
>>> from rest_framework import compat
>>> from rest_framework.settings import api_settings
>>> api_settings.DEFAULT_RENDERER_CLASSES
[<class 'rest_framework.renderers.JSONRenderer'>, <class 'rest_framework.renderers.BrowsableAPIRenderer'>]
>>> 
(drf-test) ~ $ deactivate 
~ $ rm -rf ~/Desktop/drf-test/
```

I'm going to close this as is. Happy to re-open if we can pin down an actual issue. 

> ... import into IDE...

You may need to do things like point your IDE to your `venv` etc.

**Closed by carltongibson** 2018-01-10 15:28 UTC

**Comment by wangxujie** [comment] 2018-01-11 02:39
```
Successfully installed Django-1.9
(django_env)  ⚙  ~/Desktop  python
Python 2.7.10 (default, Feb  7 2017, 00:08:15)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>  from django.conf import settings
  File "<stdin>", line 1
    from django.conf import settings
    ^
IndentationError: unexpected indent
>>> from django.conf import settings
>>> settings.configure(SECRET_KEY='123abc')
>>> from rest_framework import compat
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/wangx/Desktop/django_env/lib/python2.7/site-packages/rest_framework/compat.py", line 26, in <module>
    from django.urls import (  # noqa
ImportError: No module named urls
>>>
```
Follow your steps still wrong，Change `django.urls`  `django.core.urlxxx` ,the compat.py would be corrected.but anthor file with django.urls import  error occurred. What is the version of the problem?
```
Successfully installed djangorestframework-3.7.7
pip install Django==1.9
python 2.7.13
```

**Comment by rpkilby** [comment] 2018-01-11 03:36
Hi @wangxujie DRF 3.7 dropped support for Django 1.9 and below.
