### ISSUE TITLE
schema go wrong when include app urls.py 

### ISSUE THREAD

**Issue by allenling** [encode/django-rest-framework#5282] opened 2017-07-19 08:53 UTC
#django rest framework version 3.6.3
in project urls.py, include a app urls:

poll.views
```python

from rest_framework.views import APIView
from rest_framework.response import Response


class PollF(APIView):

    def get(self, request):
        return Response({'data': {'PollF get'}})

    def post(self, request):
        return Response({'data': {'PollF post'}})


class PollT(APIView):

    def get(self, request):
        return Response({'data': {'PollT get'}})

    def post(self, request):
        return Response({'data': {'PollT post'}})
```

 poll.urls.py
```python

from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^poll_first', views.PollF.as_view()),
    url(r'^poll_two', views.PollT.as_view()),
]
```
project urls.py
```python

url(r'^poll/', include('poll.urls')),
```
and, SchemaGenerator.get_links do not group all urls in poll. 

here is  what SchemaGenerator.get_links return 

```python
OrderedDict([

('poll_first', {'list': Link(url='/poll/poll_first', action='get'), 'create': Link(url='/poll/poll_first', action='post')}), 

('poll_two', {'list': Link(url='/poll/poll_two', action='get'), 'create': Link(url='/poll/poll_two', action='post')}),

])
```
urls in app not be included in their app, they just like two app.

i think the struct what SchemaGenerator.get_links  return should be:

```python
{'poll' : {
             'poll_first':'',
              'poll_two':'',
            } 
}
```
the key is that in SchemaGenerator.get_links, it got prefix, and create dict with subpath, we lost app in here.
```python
#  SchemaGenerator.get_links

       # got prefix, it is app name
       prefix = self.determine_path_prefix(paths)

        for path, method, view in view_endpoints:
            # path = /poll/poll_first
            if not self.has_view_permissions(path, method, view):
                continue
            link = self.get_link(path, method, view)
            # we cut the app name, subpath = /poll_first
            subpath = path[len(prefix):]
           # lost app name, keys =  ['poll_first', 'list']
            keys = self.get_keys(subpath, method, view)
           '''
           not insert into with app name, here call
           insert_into(OrderedDict(), ['poll_first', 'list'], ink()]),
           it should call
           insert_into(OrderedDict(),['app', 'poll_first', 'list'], ink()]),
           '''
            insert_into(links, keys, link)
```
so, we should insert_into with path, not the subpath, i think.

remove  
```python
prefix = self.determine_path_prefix(paths)
subpath = path[len(prefix):]
```
and replace 
```python
keys = self.get_keys(subpath, method, view)
```
with
```python
keys = self.get_keys(path, method, view) will fix that.
```

what you guys think?

**Comment by carltongibson** [comment] 2017-09-27 08:38
Hi @allenling. I'm going to close this: it's the intended behaviour. 

This only happens because you have a single app — or a single include. If you had a second group... 

```
url(r'^comment/', include('comment.urls')),
```

... or such then you'd get (both) the `poll` and `comment` grouping you expect. 

When there's a single app, there's no need to group. 

If you **really need** this just override `get_links` to wrap the returned value yourself. When you move to multiple apps you can drop this shim.

**Closed by carltongibson** 2017-09-27 08:38 UTC
Labels: Schema Generation
