### ISSUE TITLE
Django Rest Framework  - listField does not works. It gives None when object is embedded on my retrieved information. I've used MongoDB

### ISSUE THREAD

**Issue by txusdumort** [encode/django-rest-framework#6518] opened 2019-03-22 00:23 UTC
## Checklist

- [*] I have verified that that issue exists against the `master` branch of Django REST framework.
- [*] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [*] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [*] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [*] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

hi.

I've a similar problem, wen the context is described below.

I'm using MongoDB the connection is provided by Djongo, over is being used DRF to manage all request to mi API.

My data (profile) is structured like next Json object
```
{
    "name" : "profile name",
    "description" : "this is a description",
    "params" : "X1, X2,X3, etc",
    "config" : "CONFIG OF DEVICE",
    "user" : {
        "name" : "user name",
        "middle_name" : "test middle name",
        "last_name" : "test last name",
        "email" : "test@test.com",
        "institute" : {
            "name" : "MIT",
            "place" : {
                "coordinates" : [ 30.0, 101.0,  0.0 ],
                "type" : "Point"
            },
            "country" : "US"
        }
    },
    "place" : {
        "coordinates" : [  90.0, 901.0, 10.0 ],
        "type" : "Point"
    },
    "devices" : [ 
        {
            "name" : "DEVICE 1",
            "verification_code" : "",
            "verificated" : 0,
            "configuration" : "kjk",
            "places" : [ 
                {
                    "coordinates" : [ 30.0,  101.0,  0.0 ],
                    "type" : "Point"
                }, 
                {
                    "coordinates" : [  31.0, 102.0, 1.0 ],
                    "type" : "Point"
                }
            ]
        }
    ]
}
```
I know, the coordinates are wrong, but is just for test.

Well I send that object to my view and then to the ProfileSerializer, this get the responsible to check the embedded objects (each one have your own serializer). After checking data, the info is saved without problem as you can see in next picture:

![Screenshot 2019-03-21 at 14 44 05](https://user-images.githubusercontent.com/10194082/54783832-09c65700-4be8-11e9-8ef0-07678ea8cc79.png)

But the problem is when I try to. retrieve all profiles. Just the coordinates are null, Other embedded objects are retrieved in good way, only the Place Object is malformed. Next, I'll show you the response:

```
[
{
        "id": 22,
        "name": "profile name",
        "description": "this is a description",
        "params": "X1, X2,X3, etc",
        "config": "CONFIG OF DEVICE",
        "user": {
            "name": "user name",
            "middle_name": "test middle name",
            "last_name": "test last name",
            "email": "test@test.com",
            "institute": {
                "name": "MIT",
                "place": {
                    "coordinates": **null**,
                    "type": "Point"
                },
                "country": "US",
                "created_at": "2019-03-21T20:43:33.928000Z"
            },
            "created_at": "2019-03-21T20:43:33.959000Z"
        },
        "place": {
            "coordinates": **null**,
            "type": "Point"
        },
        "devices": [
            {
                "name": "DEVICE 1",
                "verificated": 0,
                "configuration": "kjk",
                "places": [
                    {
                        "coordinates": **null**,
                        "type": "Point"
                    },
                    {
                        "coordinates": **null**,
                        "type": "Point"
                    }
                ],
                "created_at": "2019-03-21T20:43:33.898000Z"
            }
        ],
        "created_at": "2019-03-21T20:43:33.976000Z"
    }
]
```

 For this questions only I'll describe/show the serializer  of one  object, but if you need some info I'll get you as soon as possible.

Models

```
class Place(models.Model):
    coordinates = models.ListField(blank=True, null=True, default=[0.0, 0.0, 0.0])
    type = models.CharField(max_length=10, default="Point")
    objects = models.DjongoManager()

class Profile(models.Model):
    name = models.CharField(max_length=200)
    description = models.TextField(default="Without Description")
    params = models.TextField(default="No params")
    config = models.CharField(max_length=200)
    user = models.EmbeddedModelField(
        model_container=User
    )
    place = models.EmbeddedModelField(
        model_container=Place
    )
    devices = models.ArrayModelField(
        model_container=Device
    )
    created_at = models.DateTimeField(auto_now_add=True)
    objects = models.DjongoManager()
```

Serializers

```
class PlaceSerializer(serializers.ModelSerializer):
    coordinates = serializers.ListSerializer(
        child=serializers.FloatField(),
    )
    class Meta:
        model = Place
        fields = ('id', 'coordinates', 'type')

class ProfileSerializer(serializers.ModelSerializer):
    user = UserSerializer( )
    place = PlaceSerializer()
    devices = DeviceSerializer( many=True)

    class Meta:
        model = Profile
        fields = ('id', 'name', 'description', 'params', 'config',
                  'user', 'place', 'devices', 'created_at')
        depth=8

    def create(self, validated_data):
        # get principal fields
        user_data = validated_data.pop('user')
        **place_data = validated_data.pop('place')**
        devices_data = validated_data.pop('devices')

        # get nested fields

        # devices nested fields
        devices = []
        for device in devices_data:
            places = []
            places_data = device.pop('places')
            for place in places_data:
                places.append( **Place(coordinates=place['coordinates'], type=place['type'])** )

            device['places'] = places
            devices.append( Device.objects.create(**device) )
        validated_data['devices'] = devices
        # user nested fields
        institute_data = user_data.pop('institute')
        place = institute_data.pop('place')
        institute_data['place'] = Place(coordinates=place['coordinates'], type=place['type'])
        user_data['institute'] = Institute.objects.create(**institute_data)
        validated_data['user'] = User.objects.create(**user_data)
        profile = Profile.objects.create(**validated_data)
        return profile
```

I've defined PlaceSerializer on many ways but all of them gets the same result, Below describe this ways

CASE 1
```
class PlaceSerializer(serializers.ModelSerializer):
    coordinates = serializers.ListSerializer(
        child=serializers.FloatField(),
    )
```

CASE 2
```
class CoordinatesSerializer(serializers.ListSerializer):
        child=serializers.FloatField()

class PlaceSerializer(serializers.ModelSerializer):
    coordinates = CoordinatesSerializer()
```

CASE 3
```
class PlaceSerializer(serializers.ModelSerializer):
    coordinates = serializers.ListField(
        child=serializers.FloatField()
    )
```

CASE 4
```
class PlaceSerializer(serializers.ModelSerializer):
    coordinates = serializers.ListField()
```

CASE 5
```
class PlaceSerializer(serializers.ModelSerializer):
    coordinates = serializers.ListSerializer()
#gives error for child is not present
```

I had changed the types, CharField, IntegerField, FloatField, etc with same results.

Another tests that I've done are append to serializer the methods create, update, to_representation, to_internal_value, all of this for to manage in a better way the info that will saved o retrieved but any works. Another curiosity, if I add a simple Listfield like [10,90,1], is saved and retrieved without problem in contrast when this ListField is inside Place Objects

Please if you know how to solve this I'll glad to you.

**Comment by xordoquy** [comment] 2019-03-22 08:45
I'm closing this as we do not support mongodb based ORM and have no idea how the integration is performed.
I'll reopen if the issue can be reproduced with a PostgresQL database or with regular serializers

**Closed by xordoquy** 2019-03-22 08:45 UTC

**Comment by txusdumort** [comment] 2019-03-22 20:18
The problem is not with MongoDB, the problem is with the serializers used in DRF. If MongoDB were the problem, the data would never have been saved, or it would be kept incomplete or something like that.

I know the problem are the serializer and DRF flow, because I made some tests retrieving the Place objects on a separate view who calling PlaceSerializer and there was the data: coordinates and type. But when the place is inside other Object, just in this case all breaks. It's Illogic!

It's easy to say if you use something different so it's no my responsible, but only trying de tool in new infrastructure we will know if that is good enough or not.

**Comment by rpkilby** [comment] 2019-03-23 00:00
Hi @txusdumort. The overall problem is that the example code is too complicated for us to look into.
- There are external dependencies
- There is a lot of extraneous code
- There is missing/unknown code
- There is no clearly stated problem

#### External dependencies:
We cannot easily test 3rd party integrations like Djongo. Not only are we not familiar with the project, we don't know how to setup an environment to test it. If Djongo is not critical for demonstrating the problem, then it should just be removed from the test code. 

#### Extraneous code:
The issue seems to be related to the serialized output, however the code sample includes the `create` method (which would be part of deserialization/saving). I'm guessing it's unrelated, but I don't know for certain. If it isn't related, then it should also be removed.

#### Missing code:
Even though the description is very verbose, there are some missing elements like the nested `DeviceSerializer` and `UserSerializer`. If those are necessary, then their code should be included. If they aren't necessary, then the code could be simplified by removing them from `ProfileSerializer`.

#### No clearly stated problem:
You provide a lot of context, which is great and provides some insight, but there is never a clearly stated bug within DRF. I know that your serializers have some unexpected null/empty fields, but aside from "this is not what I expect", I can't clearly state what your actual issue is. e.g., I would expect something along the lines of:

> Deeply nested serializers are not serializing their data and just have null values.

This statement should then be followed by an example that's as minimal as possible. e.g., a 3-5 line model, a 5-10 line serializer, and the data the serializer was initialized with. Something like:

```python
class ProblemModel(models.Model):
    problem_field = models.ProblematicFieldType(...)
    
class ProblemSerializer(serializers.ModelSerializer):
    class Meta:
        model = ProblemModel
        fields = [...]

instance = ProblemModel(problem_field='foo')
assert ProblemSerializer(instance).data == {'problem_field': 'foo'}
```
----

Does that help? In short, these kinds of issues are generally too complicated for us to be able to debug, and it needs to be simplified to a minimal example. The person who is most capable of doing that is you - the person who wrote the original code.
