### ISSUE TITLE
Is there a setting to enable .select_for_update() for all PATCH and PUT requests?

### ISSUE THREAD

**Issue by dmugtasimov** [encode/django-rest-framework#6392] opened 2019-01-05 14:37 UTC
If it is not there. Why not to add it or just do `.select_for_update()` by default?

**Comment by dmugtasimov** [comment] 2019-01-05 15:30
Something like:

```
class CustomGenericAPIView(GenericAPIView):
    def get_queryset(self):
        qs = super(CustomGenericAPIView, self).get_queryset()
        if self.request.method in ('PATCH', 'PUT'):
            qs = qs.select_for_update()

        return qs


class CustomGenericViewSet(ViewSetMixin, CustomGenericAPIView):
    pass


class CustomModelViewSet(mixins.CreateModelMixin,
                         mixins.RetrieveModelMixin,
                         mixins.UpdateModelMixin,
                         mixins.DestroyModelMixin,
                         mixins.ListModelMixin,
                         CustomGenericViewSet):
    pass

```

**Comment by tomchristie** [comment] 2019-01-07 14:55
Duplicate of #4675, #2648

**Closed by tomchristie** 2019-01-07 14:55 UTC
