### ISSUE TITLE
When will Django 3.2 be supported?

### ISSUE THREAD

**Issue by fabtjar** [encode/django-rest-framework#7992] opened 2021-05-17 14:37 UTC
The requirements doesn't show Django 3.2 yet: https://www.django-rest-framework.org/#requirements

If anyone is working on getting 3.2 support do you know when this will be out?

**Comment by carltongibson** [comment] 2021-05-17 14:56
It's already supported. See https://github.com/encode/django-rest-framework/discussions/7944

Duplicate of #7944

**Closed by carltongibson** 2021-05-17 14:56 UTC
