### ISSUE TITLE
use_pk_only_optimization method on PrimaryKeyRelatedField is not documented

### ISSUE THREAD

**Issue by KushGoyal** [encode/django-rest-framework#5243] opened 2017-06-29 16:29 UTC
PrimaryKeyRelatedField does not work properly if you don't use a specific queryset.

for example:

```python
my_field = PrimaryKeyRelatedField(queryset=MyModel.objects.all())
```

If I use the above field it will give me json serialization error in response. Since`use_pk_only_optimization` is set to true and the field assumes that the objects returned by the queryset are pk objects. But instead they are full objects.

While this will work fine:
```python
my_field = PrimaryKeyRelatedField(queryset=MyModel.objects.all().values_list('pk', flat=True))
```

This behaviour of PrimaryKeyRelatedField field is undocumented on page [1]. It would really help a lot if this behaviour is explicitly mentioned and users know which queryset to use.

`MyModel.objects.all()` will work fine for write_only cases but not for read and write both.

[1] http://www.django-rest-framework.org/api-guide/relations/?q=use_pk_only_optimization#primarykeyrelatedfield

**Comment by xordoquy** [comment] 2017-06-30 06:51
https://github.com/encode/django-rest-framework/blob/master/tests/test_relations.py#L110 test case should already cover this use case.

**Comment by KushGoyal** [comment] 2017-06-30 07:02
If `use_pk_only_optimization` is set the true the instance is of type `PKOnlyObject` and the attribute `pk` on the instance can be the whole object. I think this behaviour needs to be documented.

**Comment by xordoquy** [comment] 2017-07-04 08:06
Adding `use_pk_only_optimization` to the documentation means it won't be a private part any longer and will be harder to change and we want to avoid that.

**Comment by KushGoyal** [comment] 2017-07-04 09:13
Sure, I get that. When we need is to mention the queryset for `PrimaryKeyRelatedField` for supporting serialization of data in GET requests. The queryset should be `model.objects.all().values('pk', flat=True)`. This queryset supports read and write both. While querysets which return whole objects like `model.objects.all()` cannot be used for GET requests.

**Comment by xordoquy** [comment] 2017-07-04 09:16
I'm fine with that.
Would appreciate another opinion here.

**Comment by tomchristie** [comment] 2017-07-12 16:12
> MyModel.objects.all() will work fine for write_only cases but not for read and write both.

Can you expand on that. The queryset is *only* used for checking updates, so I'm unclear about exactly what isn't working when making a GET request.

> If I use the above field it will give me json serialization error in response. 

Could you give an example of that.

I don't think there's a documentation issue, but there could be something else to unpick here (or not) you shouldn't need to use `.values_list('pk', flat=True)` and our test cases *seem* to suggest that the existing behavior works as expected. If it doesn't then that's something we need to look into further.

**Comment by tomchristie** [comment] 2017-07-12 16:21
> If I use the above field it will give me json serialization error in response. 

Couldn't reproduce any error, using `If I use the above field it will give me json serialization error in response. `

Happy to reconsider this issue, given a traceback and more information, but closing in its current state.

**Closed by tomchristie** 2017-07-12 16:21 UTC
Labels: Needs information
