### ISSUE TITLE
Feature Request: generateschema should parse query string parameters in Docstring

### ISSUE THREAD

**Issue by rpaknahad** [encode/django-rest-framework#7213] opened 2020-03-04 06:09 UTC
Using DRF`s generateschema command, Docstring inline documentations are automatically parsed, but there is no way to add extra query parameters or document existing parameters inside that Docstring.
Here is an example:

```
@action(detail=False, methods=['post'])
def add(self, request):
  """
  Adds a new account
  parameters:
  - in: query
    name: service_id
    type: string
    required: true
    description: Identifier of the service
"""
```

**Comment by carltongibson** [comment] 2020-03-04 07:04
This was added in #6898 which was part of 3.11 

Duplicate of #7212. The [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) is the best place to take this discussion and other usage questions. Thanks!

**Closed by carltongibson** 2020-03-04 07:04 UTC
