### ISSUE TITLE
Authentication changing the way the parser negotiation happens

### ISSUE THREAD

**Issue by aidanlister** [encode/django-rest-framework#5278] opened 2017-07-17 08:53 UTC
Hello,

We are seeing some really weird behaviour in our testcase below, with the first test failing (because there's no parser for application/json) but the second test passing? How is it possible the authentication method changes the parser negotiation? I've stepped through the whole codebase and can't work it out.

```
class BulkAPITests(BaseAPITestCase):
    def setUp(self):
        super().setUp()
        self.superuser = AdminFactory()


    def test_auth_token(self):
        self.app = OauthApplicationFactory(user=self.superuser)
        secret = self.app.client_id + ':' + self.app.client_secret
        self.auth_headers = {
            'HTTP_AUTHORIZATION': b'Basic ' + base64.b64encode(secret.encode('utf-8')),
        }
        data = {
            'grant_type': 'password',
            'username': self.superuser.email,
            'password': 'password',
        }
        response = self.client.post('/api/oauth2/token/', data=data, **self.auth_headers)
        self.assertEqual(response.status_code, 200)
        resp_json = json.loads(response.content.decode('utf8'))
        access_token = resp_json['access_token']
        self.client.credentials(HTTP_AUTHORIZATION='Bearer {}'.format(access_token))
        self.test_users = [StaffFactory() for x in range(0, 2)]
        self.test_branches = [BranchFactory() for x in range(0, 3)]
        post_data = {
            'ids': [user.id for user in self.test_users],
            'add_branches': [branch.id for branch in self.test_branches],
        }
        response = self.client.patch('/api/v2/users/', data=json.dumps(post_data), content_type='application/json')
        self.assertEqual(response.status_code, 200, f"{response.content}")


    def test_session_based_auth(self):
        self.client.force_authenticate(user=self.superuser)
        self.test_users = [StaffFactory() for x in range(0, 2)]
        self.test_branches = [BranchFactory() for x in range(0, 3)]
        post_data = {
            'ids': [user.id for user in self.test_users],
            'add_branches': [branch.id for branch in self.test_branches],
        }
        response = self.client.patch('/api/v2/users/', data=json.dumps(post_data), content_type='application/json')
        self.assertEqual(response.status_code, 200, f"{response.content}")
```

**Comment by xordoquy** [comment] 2017-07-17 09:01
> with the first test failing (because there's no parser for application/json)

What are the status codes ?
What is the returned error content ?

If you think there's a bug in DRF we will need the simplest test case that demonstrate the issue that we can reproduce.

**Comment by tomchristie** [comment] 2017-07-17 09:01
I'm going to have to close this one off, as it's not narrowed down enough.

**Closed by tomchristie** 2017-07-17 09:01 UTC
Labels: Needs information

**Comment by tomchristie** [comment] 2017-07-17 09:04
Sorry not to be more help @aidanlister - If you can reduce this to a clearer "I think there's a bug in the framework because X" then we can look into it.

> How is it possible the authentication method changes the parser negotiation?

It doesn't, but worth trying to nail down your problem to the *simplest possible* reproducible case, and keeping any eye out if there's any bits that might be introducing unexpected side effects. 
Modifying class attributes on CBVs can be a bit of a gotcha,  could be that you've got something like that that's causing problems.
