### ISSUE TITLE
[bug] paginate_queryset should return an empty iterable not None

### ISSUE THREAD

**Issue by rosscdh** [encode/django-rest-framework#7393] opened 2020-06-29 06:22 UTC
## Checklist

- [x ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

1. call paginate_queryset on a qs that returns no results
2. the paginate queryset returns None and not Queryset.none

## Expected behavior

* the paginate_queryset should return an empty iterable so that it can be used pythonically in loops
* an if statement is jarring

```
for item in self.paginate_queryset(self.app.batch_set.all()):
   # do stuff, but nothing happens if the qs is empty
```
## Actual behavior

* if statements

```
        page_qs = self.paginate_queryset(self.app.batch_set.all())
        if page_qs:
            for rb in page_qs:
```

Happy to submit a PR if this is an issue

**Comment by rpkilby** [comment] 2020-07-01 15:50
Hi @rosscdh.

> the paginate_queryset should return an empty iterable so that it can be used pythonically in loops

When pagination returns `None`, this indicates that pagination was not performed (e.g., because pagination was not configured for the view). In contrast, an empty result might imply that pagination _was_ performed, but happened to return an empty result. It is important that these two cases have distinct results.

> the paginate queryset returns None and not Queryset.none

Note that pagination should generally return a list, not a queryset. So, returning an queryset.none would be incorrect.

Happy to continue discussing additional questions, but closing as pagination is working as intended.

**Closed by rpkilby** 2020-07-01 15:50 UTC
