### ISSUE TITLE
ModelSerializer default querysets

### ISSUE THREAD

**Issue by bobort** [encode/django-rest-framework#5358] opened 2017-08-23 21:03 UTC
Some of my `ForeignKey`s in my models use the `limit_choices_to` argument.  I was a bit surprised to find that the auto-generated forms did not follow the same rules, so I find myself overriding the queryset argument used in my custom `ModelSerializer` class.

I've never contributed source code to a project, and I really don't know how to do it, but I would like to propose the following replacement to rest_framework/relations.py, line 158:

```
            if hasattr(self.parent, "Meta") and hasattr(self.parent.Meta, "model"):
                queryset = queryset.filter(
                    **self.parent.Meta.model._meta.get_field(self.source).get_limit_choices_to()
                )
            else:
                queryset = queryset.all()
```

Truth be told, there's a comment in there about `repr` output, and my worthless opinion is that you have an incredibly bizarre reason to pass around `Manager`s from the `ModelSerializer` instead of `QuerySet`s.  Isn't there a way to obtain the manager from a `QuerySet` object so that you can create your own custom `repr` for them if they're really that important for everyone?  But, I digress...

**Comment by rpkilby** [comment] 2017-08-23 21:19
Here's a fixed [link](https://github.com/encode/django-rest-framework/blob/3.6.4/rest_framework/relations.py#L149-L159) to the relevant method.

**Comment by tomchristie** [comment] 2017-10-03 12:37
Okay, we could accept a pull request along those lines, and start by seeing if breaks any of the existing tests or not.

**Comment by carltongibson** [comment] 2017-11-23 08:01
This is a duplicate of #1811. Closing as such.

**Closed by carltongibson** 2017-11-23 08:01 UTC
