### ISSUE TITLE
TypeError in test.py for requests

### ISSUE THREAD

**Issue by niebloomj** [encode/django-rest-framework#5213] opened 2017-06-13 14:35 UTC
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
`python manage.py test --noinput alloy.modules.super_tester`

```
class SuperTester(APITestCase):

	def test1(self):
		client = APIClient()
		data = client.get('/')
		print(data)
```
## Expected behavior
I expect that this see the data of the json that the get request produces. 
This used to work and all my integration tests were passing.

## Actual behavior
```
======================================================================
ERROR: test1 (alloy.modules.super_tester.SuperTester)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/Jacob/Dropbox/Github/edu-chat-core/alloy/modules/super_tester.py", line 15, in test1
    data = client.get('/')
  File "/Users/Jacob/Dropbox/Github/edu-chat-core/educhatenv/lib/python3.6/site-packages/rest_framework/test.py", line 282, in get
    response = super(APIClient, self).get(path, data=data, **extra)
  File "/Users/Jacob/Dropbox/Github/edu-chat-core/educhatenv/lib/python3.6/site-packages/rest_framework/test.py", line 208, in get
    return self.generic('GET', path, **r)
  File "/Users/Jacob/Dropbox/Github/edu-chat-core/educhatenv/lib/python3.6/site-packages/django/test/client.py", line 416, in generic
    return self.request(**r)
  File "/Users/Jacob/Dropbox/Github/edu-chat-core/educhatenv/lib/python3.6/site-packages/rest_framework/test.py", line 279, in request
    return super(APIClient, self).request(**kwargs)
  File "/Users/Jacob/Dropbox/Github/edu-chat-core/educhatenv/lib/python3.6/site-packages/rest_framework/test.py", line 231, in request
    request = super(APIRequestFactory, self).request(**kwargs)
  File "/Users/Jacob/Dropbox/Github/edu-chat-core/educhatenv/lib/python3.6/site-packages/django/test/client.py", line 483, in request
    response = self.handler(environ)
  File "/Users/Jacob/Dropbox/Github/edu-chat-core/educhatenv/lib/python3.6/site-packages/django/test/client.py", line 131, in __call__
    self.load_middleware()
  File "/Users/Jacob/Dropbox/Github/edu-chat-core/educhatenv/lib/python3.6/site-packages/django/core/handlers/base.py", line 82, in load_middleware
    mw_instance = middleware(handler)
TypeError: __init__() takes 1 positional argument but 2 were given
```

**Comment by xordoquy** [comment] 2017-06-14 06:33
From the traceback it looks like it's an issue with one of your middleware.
Closing this as we do have a lot of working similar code and therefore are not able to reproduce it.

**Closed by xordoquy** 2017-06-14 06:33 UTC
