### ISSUE TITLE
Missing pyyaml schema dependency should raise user-friendly error

### ISSUE THREAD

**Issue by prakhar-goel** [encode/django-rest-framework#6331] opened 2018-11-23 15:39 UTC
## Checklist

- [ ] I have verified that that issue exists against the `master` branch of Django REST framework.
- [ ] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [ ] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [ ] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [ ] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce

- Clone repo git@github.com:encode/rest-framework-tutorial.git
- `cd rest-framework-tutorial`
- `mkvirtualenv -p python3 drf-testing`
- `vim requirements.txt` and overwrite it with following dependencies (upgraded django and other dependencies.)
```
certifi==2018.10.15
chardet==3.0.4
coreapi==2.3.3
coreschema==0.0.4
dj-database-url==0.5.0
Django==2.1.3
djangorestframework==3.9.0
gunicorn==19.9.0
idna==2.7
itypes==1.1.0
Jinja2==2.10
Markdown==3.0.1
MarkupSafe==1.1.0
psycopg2==2.7.6.1
Pygments==2.2.0
pytz==2018.7
requests==2.20.1
uritemplate==3.0.0
urllib3==1.24.1
whitenoise==4.1.2
```
- `python manage.py migrate`
- `python manage.py runserver`

Open http://localhost:8000/schema

## Expected behavior
You should see the API schema like below:
<img width="1193" alt="screen shot 2018-11-23 at 9 02 43 pm" src="https://user-images.githubusercontent.com/1198834/48951094-48fad900-ef63-11e8-9262-d67c4bfecc70.png">

## Actual behavior
You get error:
```
AttributeError at /schema/
'Request' object has no attribute 'accepted_renderer'

Request Method:	GET
Request URL:	http://localhost:10001/schema/
Django Version:	2.1.3
Exception Type:	AttributeError
Exception Value:	
'Request' object has no attribute 'accepted_renderer'
Exception Location:	/Users/prakhar/virtualenvs/drf-testing/lib/python3.6/site-packages/rest_framework/request.py in __getattr__, line 414
Python Executable:	/Users/prakhar/virtualenvs/drf-testing/bin/python
Python Version:	3.6.5
```
## Current Solution
Reverting to DRF version 3.8.0 fixes the problem. 

- `pip install djangorestframework==3.8.0` and `python manage.py runserver`
- Open browser. Schema should be visible now.

**Comment by carltongibson** [comment] 2018-11-23 17:05
Duplicate of #6300?

**Comment by tomchristie** [comment] 2019-01-08 11:50
All the same we clearly shouldn't be push such an obscure error message onto our users for this case. Is there an open ticket to addressing that part?

**Comment by rpkilby** [comment] 2019-02-21 03:06
I don't think so? Reopening just in case.

**Comment by Cjkjvfnby** [comment] 2020-04-08 07:14
Looks like it can be closed.  

https://github.com/encode/django-rest-framework/blob/6a23fa06495c6010239dda926f55f2d6baa79cf3/rest_framework/schemas/openapi.py#L261

**Comment by auvipy** [comment] 2020-07-30 04:32
> Looks like it can be closed.
> 
> https://github.com/encode/django-rest-framework/blob/6a23fa06495c6010239dda926f55f2d6baa79cf3/rest_framework/schemas/openapi.py#L261

Based on this should we consider closing the issue?

**Comment by rpkilby** [comment] 2020-08-05 23:58
Thanks  @Cjkjvfnby.

**Closed by rpkilby** 2020-08-05 23:58 UTC
Labels: Cleanup
