### ISSUE TITLE
rest_framework.serializers.BooleanField(required=False) default value is not empty

### ISSUE THREAD

**Issue by TonyMistark** [encode/django-rest-framework#8730] opened 2022-10-25 04:01 UTC
## example code
```
from rest_framework.serializers import Serializer
from rest_framework.serializers import BooleanField
from django.http import QueryDict

class S(Serializer):
    b = BooleanField(required=False)
s = S(data=QueryDict())
s.is_valid(raise_exception=True)
s.validated_data
# OrderedDict([('b', False)])

# Another way

s = S(data={})
s.is_valid(raise_exception=True)
s.validated_data
# OrderedDict()
```
passing QueryDict() and {}, two empty dict, types are rarely different， but get a completely different result: `OrderedDict([('b', False)])` and `OrderedDict()`, It's a little bit inconsistent

field b should not in s.validated_data, because I'm not set BooleanField default=False: BooleanField(required=False, default=None)
[S(data=QueryDict(), partial=True) can probably be fixed, but it's not elegant. If I didn't set the default, it shouldn't be set for me, it should be empty](https://github.com/encode/django-rest-framework/blob/master/rest_framework/fields.py#L426)

**Comment by winmorre** [comment] 2022-10-25 08:26
So looking at the to_representation of the BooleanField, it returns a bool(value). if the value is None it returns False. 
`
    def to_representation(self, value):
        if value in self.TRUE_VALUES:
            return True
        elif value in self.FALSE_VALUES:
            return False
        if value in self.NULL_VALUES and self.allow_null:
            return None
        return bool(value)
`
In python the bool(None) is false.

@TonyMistark  In your case, will you want the to_representation of the BooleanField to return None if the `value` is None?

**Comment by winmorre** [comment] 2022-10-25 08:32
I think the to_representation of the BooleanField returning False for a None value is elegant. Because Booleans only have two values. I think the default value is not empty as you expected because an empty boolean value is still `False` .

**Comment by TonyMistark** [comment] 2022-10-25 09:53
> I think the to_representation of the BooleanField returning False for a None value is elegant. Because Booleans only have two values. I think the default value is not empty as you expected because an empty boolean value is still `False` .

In my case, I'm not passing a value to this method， and the b = BooleanField(required=False), required=False, In my opinion, I did not pass the value to the optional field, so the key `b` should not appear in the `s.validated_data`, like others type Field

**Comment by TonyMistark** [comment] 2022-10-25 10:26
> I think the to_representation of the BooleanField returning False for a None value is elegant. Because Booleans only have two values. I think the default value is not empty as you expected because an empty boolean value is still `False` .

I'm not passing a value to this Serializer, the BooleanField's `to_representation` method should not be called at all

**Comment by winmorre** [comment] 2022-10-25 18:11
Picking this up.

**Comment by kevin-brown** [comment] 2022-10-27 02:55
I believe this is a duplicate of https://github.com/encode/django-rest-framework/issues/8300 and as such I'm going to close this and point continued discussion to that pre-existing ticket. I'll note this has also been officially addressed in https://github.com/encode/django-rest-framework/issues/6969#issuecomment-538355621 but it's been a few years and there might be a better way now, so I'll leave the duplicate ticket open.

**Closed by kevin-brown** 2022-10-27 02:55 UTC
