### ISSUE TITLE
'NoneType' object has no attribute 'user' while accessing docs api and get_serializer_class(self)

### ISSUE THREAD

**Issue by alex1vanchik** [encode/django-rest-framework#5433] opened 2017-09-19 21:57 UTC
## Checklist

-  [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](http://www.django-rest-framework.org/topics/third-party-resources/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
create like [example](http://www.django-rest-framework.org/api-guide/generic-views/#get_serializer_classself) in your doc 
```
def get_serializer_class(self):
    if self.request.user.is_staff:
        return FullAccountSerializer
    return BasicAccountSerializer
```
## Expected behavior
The schema must be generated
## Actual behavior
Error 'NoneType' object has no attribute 'user'. 
All because when a schema is creating in the get_serializer_class  self.request = None

**I'm not sure but it looks like a bug [#5198](https://github.com/encode/django-rest-framework/issues/5198).** I think it will be useful

**Comment by anshengme** [comment] 2017-09-20 01:29
I also encountered the same problem when generating API documentation, self.request == None

**Comment by carltongibson** [comment] 2017-09-20 09:20
This is (indeed) a duplicate of #5198. 

The bottom line is you can't rely on `request.user` being set in schema generation contexts — so you'll need to handle that case in your `get_serializer_class` method. 

Related is the discussion on #5142 — whilst you _can_ pass a request to `get_docs_view` sets `public=True` which removes the request from being passed to the view. (See https://github.com/encode/django-rest-framework/issues/5142#issuecomment-303352648) 

We'll narrow down and improve the behaviour here. For now make sure you can handle request being None.

**Closed by carltongibson** 2017-09-20 09:20 UTC
