### ISSUE TITLE
request.FILES  close

### ISSUE THREAD

**Issue by dilyanpalauzov** [encode/django-rest-framework#5209] opened 2017-06-12 10:16 UTC
Django closes transparently the elements of requests.FILES since https://github.com/django/django/pull/2747/ , but Django Rest Framework forgets doing so.  In particular it leaves  /tmp/*.upload files.

**Comment by xordoquy** [comment] 2017-06-12 10:24
Django REST framework system is built on top of Django's. Moreover, I've seen cases where test failed because the file was closed during the API call.
I'm closing the issue due to the lack of evidences.
Will reconsider with a failing test case we can reproduce.

**Comment by dilyanpalauzov** [comment] 2017-06-12 12:40
[demo.zip](https://github.com/encode/django-rest-framework/files/1068133/demo.zip)

Here `curl -F file=@/tmp/fff http://localhost:8080/A/` does  not leave /tmp/.....upload file, but `curl -F file=@/tmp/fff http://localhost:8080/Z/` does.

Note  `FILE_UPLOAD_HANDLERS = ['django.core.files.uploadhandler.TemporaryFileUploadHandler']`

**Comment by rpkilby** [comment] 2017-07-06 17:51
Hi @dilyanpalauzov - the demo definitely demonstrates that temporary files remain after the request has been processed by DRF. DRF's stream processing is preempting Django's own data/files handling, so the underlying Django request object doesn't have any `_files` to close. 

Would you be willing to open a PR with a failing test case?

**Comment by dilyanpalauzov** [comment] 2017-07-06 17:54
I do not have the time to delve how to write test cases.

**Closed** 2017-07-10 12:42 UTC
