### ISSUE TITLE
Django Rest Framework Saying Non-Required Field Is Required

### ISSUE THREAD

**Issue by bigbob556677** [encode/django-rest-framework#6292] opened 2018-10-30 15:39 UTC
**The Backstory**

In Django I have the models

```
class Company(models.Model):
    name = models.TextField(null=False,unique=True)
    date_added = models.DateTimeField(auto_now_add=True)

class Address(models.Model):
    street = models.TextField()

class Person(models.Model ): 
    firstname = models.TextField()
    address = models.ForeignKey(Address,null= True,on_delete=models.SET_NULL)
    company = models.ForeignKey(Company,null=True,on_delete=models.SET_NULL)
```
Where each person has an address and a company.(both non required fields)

In DRF I have the serializers.

```
class AddressSerializer(serializers.ModelSerializer):
    class Meta:
        model = Address
        fields = '__all__'

class CompanySerializer(serializers.ModelSerializer):

    class Meta:
        model = Company
        fields = "__all__"

class PersonSerializer(serializers.ModelSerializer):

    class Meta:
        model = Person
        fields = ('id', 'firstname',  'address','company')

    def to_representation(self, instance):
        response = super().to_representation(instance)
        response['address'] = AddressSerializer(instance.address).data
        response['company'] = CompanySerializer(instance.company).data
        return response
```
and the ViewSets

```
class PersonViewSet(viewsets.ModelViewSet,UpdateModelMixin):
    queryset = Person.objects.all()
    serializer_class = PersonSerializer
    filter_backends = (OrderingFilter,DjangoFilterBackend,SearchFilter)
    filter_fields = ('id','company','firstname','middlename','lastname',)
    search_fields = ('firstname','middlename','lastname',)

class CompanyViewSet(viewsets.ModelViewSet,UpdateModelMixin):
    queryset = Company.objects.all()
    serializer_class = CompanySerializer
    filter_backends = (OrderingFilter,DjangoFilterBackend,SearchFilter)
    filter_fields = ('id','name',)
    search_fields = ('name',)

class AddressViewSet(viewsets.ModelViewSet,UpdateModelMixin):
    queryset = Address.objects.all()
    serializer_class = AddressSerializer
    filter_backends = [DjangoFilterBackend]
    filter_fields = ['id','street']
```
**The Issue**

When posting the data {"firstname":"foo"} to this serializer, it returns a 400 error code saying. {"company": ["This field is required."]}.

The odd thing is, the address field is set up the _seemingly_ exact same way as the company field but does not throw this error.

In order to make this work, you must post {"firstname":"foo","company":null} to the serializer, which seems a little silly considering that the address field works just fine.

Does anybody have any idea what would be causing this issue and how to prevent this from happening?

(Posted At
https://stackoverflow.com/questions/53067449/django-rest-framework-saying-non-required-field-is-required )

(Possibly related to https://github.com/encode/django-rest-framework/issues/6254#issue-371501368)

**Comment by duoi** [comment] 2018-10-31 03:41
Try setting `null=True, blank=True, default=None`.

Although a field is nullable, `blank` is the argument that sets whether or not a blank submission can take place in a form.

**Comment by rpkilby** [comment] 2018-10-31 06:38
The interesting issue is the apparent inconsistency in handling between company and address. But yes, @duoi is correct that the nullable does not mean optional.

**Comment by rpkilby** [comment] 2018-11-01 02:32
Yeah. @philip556677 thanks for the info. Would you mind creating a PR with a failing test case? If not, that's fine - there should be enough info here to put one together.

**Comment by philip556677** [comment] 2018-11-01 21:54
Ill put one together. Although other users used the exact same settings as provided and it worked. A heck of an edge case. @rpkilby

**Comment by carltongibson** [comment] 2019-02-25 09:53
This is essentially the same problem as  #6254. See there for links to the source but, for forward relations we're able to perform better introspection than for reverse relations. Happy for someone to look at improving that. 

Duplicate of #6254

**Closed by carltongibson** 2019-02-25 09:53 UTC
