### ISSUE TITLE
OpenAPI: Object of type __proxy__ is not JSON serializable

### ISSUE THREAD

**Issue by LodrikMtl** [encode/django-rest-framework#6840] opened 2019-07-28 04:11 UTC
## Checklist

- [x] I have verified that that issue exists against the `master` branch of Django REST framework.
- [x] I have searched for similar issues in both open and closed tickets and cannot find a duplicate.
- [x] This is not a usage question. (Those should be directed to the [discussion group](https://groups.google.com/forum/#!forum/django-rest-framework) instead.)
- [x] This cannot be dealt with as a third party library. (We prefer new functionality to be [in the form of third party libraries](https://www.django-rest-framework.org/community/third-party-packages/#about-third-party-packages) where possible.)
- [x] I have reduced the issue to the simplest possible case.
- [ ] I have included a failing test as a pull request. (If you are unable to do so we can still accept the issue.)

## Steps to reproduce
I have this basic setup:
#/schema/urls.py
![image](https://user-images.githubusercontent.com/26026137/62001234-3587ab00-b0ba-11e9-951e-e95324f42885.png)
#/project/urls.py
![image](https://user-images.githubusercontent.com/26026137/62002102-a8e5e880-b0cb-11e9-94cf-9284738d7534.png)
#/accounts/urls.py
![image](https://user-images.githubusercontent.com/26026137/62002129-14c85100-b0cc-11e9-939a-d4ac2ce8b4b1.png)

If I remove the users endpoint, I will got no error. Unfortunately, I can't access the schema because I don't have the permission even tho I'm a superuser.

## Expected behavior
I should see an OpenAPI Schema in JSON.

## Actual behavior
I have the following:
![image](https://user-images.githubusercontent.com/26026137/62001216-d88bf500-b0b9-11e9-8857-d920fd8364b0.png)
[trace.txt](https://github.com/encode/django-rest-framework/files/3438796/trace.txt)

## Extra
When I'm looking at the traceback, it seems that the data has been well formed. The error is raise in JSONOpenAPIRenderer when the data are being dumped/rendered. It comes from the JSON Native library of python

## NB
I'm a newbie with Django REST Framework and Django. It is possible that I have misconfigure a setting, but I looked for and didn't find anything weird.

**Comment by carltongibson** [comment] 2019-07-28 06:02
Can you put a breakpoint in to show the generated schema? As it is, not at all sure where this `__proxy__` object is coming from.

**Comment by LodrikMtl** [comment] 2019-07-28 15:29
I try with the commandline and I got the same error. It's only happening when i'm trying to create an output in an .json format. I was able to did it successfully in .yaml.

Data before being rendered/dumped in JSONOpenAPIRenderer :
[data.txt](https://github.com/encode/django-rest-framework/files/3439304/data.txt)

Data being generated with Yaml Commandline generateschema:
[schema.txt](https://github.com/encode/django-rest-framework/files/3439305/schema.txt)

Also, i'm using djangorestframework-jsonapi. Can it be a problem from this package. The commandline shouldn't be affected if it was the case. right?

**Comment by carltongibson** [comment] 2019-07-28 16:43
OK, the YAML has this in it: 

```
description: &id001 !!python/object/apply:django.utils.functional._lazy_proxy_unpickle
- !!python/name:django.utils.translation.gettext ''
- !!python/tuple
  - Required. 150 characters or fewer. Letters, digits and @/./+/-/_
    only.
- {}
- !!python/name:builtins.str ''
```

This looks like a Duplicate of #6832. Can you try against the latest `master`, and see if the issue is resolved? (Thanks!)

**Comment by LodrikMtl** [comment] 2019-07-28 20:23
Yes, I try with the latest master and it's fixed. 💯 
Thanks!

**Closed** 2019-07-28 20:24 UTC
Labels: Needs information

**Comment by carltongibson** [comment] 2019-07-29 05:13
Super. Thanks for the confirmation. Update this week I’d guess. /cc @tomchristie
