### ISSUE TITLE
Using type annotations for deserialization/validation in api_views

### ISSUE THREAD

**Issue by rsinger86** [encode/django-rest-framework#6929] opened 2019-09-15 02:52 UTC
DRF's model-backed serializers are awesome for productivity and get me 70% there for many projects. However, I find it a bit awkward to use serializers for non-CRUD resources. I often do, so my project is consistent in how it validates incoming data. But it often feels like overkill to define an whole serializer class and there's cognitive overhead in having to locate that definition to understand the parameters. 

So I was recently inspired by Instagram's [recent post](https://instagram-engineering.com/types-for-python-http-apis-an-instagram-story-d3c3a207fdb7) on how they integrated types for Django HTTP endpoints. I think it'd be awesome if DRF had a version of api_view that did something similar... 

```python
@typed_api_view("GET")
def search_movies(request, year: int, actors: List[str], title: str):
    # ORM logic
    return Reponse(data)
```
Encode's [TypeSystem library](https://github.com/encode/typesystem) could be used to annotate and validate complex data types sent by PUT or POST requests.

```python
import typesystem

class Album(typesystem.Schema):
    title = typesystem.String(max_length=100)
    release_date = typesystem.Date()

@typed_api_view("POST")
def create_album(request, account: Album):
    # ORM logic
    return Reponse(data)
```
I'd love to hear some feedback and I'd be happy to work on this either as a 3rd-party library or an eventual addition to the main codebase.

**Comment by carltongibson** [comment] 2019-09-15 07:36
This would be super to see, as a third-party library to begin. (There was a recent ticket on Dataclasses which is related...) From there maybe there’s things we could pull in. 

Closing but happy to discuss!

**Closed** 2019-09-15 07:36 UTC

**Comment by rsinger86** [comment] 2019-09-15 18:44
Great, that's good to know. It almost seems like this could primarily be a third-party package for Django, with some DRF-specific bindings. At first glance, using type annotations to validate/cast view parameters seems independent of DRF's view constructs.

I assume this is the related issue on dataclasses?
https://github.com/encode/django-rest-framework/issues/6021

**Comment by oxan** [comment] 2019-09-15 19:36
Yes, something like this would be a nice feature. It's actually reasonably easy to implement, if you use some serializer that can serialize to/from arbitrary class definitions. E.g. with my [DataclassSerializer](https://github.com/oxan/djangorestframework-dataclasses) serializer, this can be done by changing the `handler` invocation in `APIView#dispatch` to call a method like this:

```python
    def call_handler(self, handler, request, *args, **kwargs):
        serializer_context = {'request': self.request, 'format': self.format_kwarg, 'view': self}

        if 'body' in handler.__annotations__:
            body_type = handler.__annotations__['body']
            assert dataclasses.is_dataclass(body_type)

            serializer = DataclassSerializer(data=request.data, dataclass=body_type, context=serializer_context)
            serializer.is_valid(raise_exception=True)

            kwargs['body'] = serializer.validated_data

        response = handler(request, *args, **kwargs)

        if dataclasses.is_dataclass(response):
            serializer = DataclassSerializer(instance=response, dataclass=response.__class__, context=serializer_context)
            response = Response(serializer.data)

        return response
```
(I didn't test this, and I think it only supports POST/PUT, but the idea should be clear).

The biggest issue I see is that it's not really trivial to override the `handler` call in `APIView#dispatch` without duplicating the whole method. It'd be nice if that call was moved to a separate method, so that it's easier to override it and do some pre- and post-processing of the data passed to the view method. It also doesn't seem to be trivial to extend the `@api_view` decorator to use a child class of `APIView` without duplicating a lot of code.

**Comment by rsinger86** [comment] 2019-09-15 20:07
I'm having trouble understanding how the DataclassSerializer could be integrated as a type annotation. Something like this?

```python
from serializers import MyDataClassSerializer

@typed_api_view("POST")
def create_album(request, album: MyDataClassSerializer):
    # i'm confused ... is album an instance of a dataclass or a serializer?
    return data
```
Could you provide an example of how it would interface with the view?

**Comment by oxan** [comment] 2019-09-18 17:03
@rsinger86 This integration is just conceptual at the moment, but I'd like to make something like this work with automatic serialization and deserialization:

```python
@typed_api_view("POST")
def create_album(request, album: Album):
   # album is an instance of a dataclass
   return album
```

As long as your type annotations are complete, there should be no need to explicitly define a serializer. Most serializer definitions are just a duplicate of the information in the underlying class anyway.

**Comment by rsinger86** [comment] 2019-10-03 22:59
@carltongibson @tomchristie @oxan 
I implemented this "typed annotations for auto validation/sanitization" idea here:
https://github.com/rsinger86/drf-typed-views

I'm still ironing out some kinks and writing tests, but the basic workings are there.
